### ISSUE TITLE
Erroneous YAML syntax in troubleshooting article

### ISSUE THREAD

**Issue by NoSuchCommand** [scaleway/docs-content#3746]
The following YAML line should be indented one level:

https://github.com/scaleway/docs-content/blob/72bb5d51745ac0e4b466c3619005c49ae0f35b85/compute/instances/troubleshooting/fix-dns-routed-ipv6-only-debian-bullseye.mdx?plain=1#L117

Otherwise, following the procedure described in the article leads to an error at the instance's boot:

```
Traceback (most recent call last):
  File "/usr/bin/cloud-init", line 33, in <module>
    sys.exit(load_entry_point('cloud-init==24.1.7', 'console_scripts', 'cloud-init')())
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 1120, in main
    retval = util.log_time(
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2827, in log_time
    ret = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 694, in status_wrapper
    paths = read_cfg_paths()
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/devel/__init__.py", line 22, in read_cfg_paths
    init.read_cfg()
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 275, in read_cfg
    self._cfg = self._read_cfg(extra_fns)
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 286, in _read_cfg
    paths = initial_config.get("system_info", {}).get("paths", {})
AttributeError: 'NoneType' object has no attribute 'get'
[FAILED] Failed to start Initial cloud-init job (pre-networking).
```

**Comment by bene2k1** [comment]
Hello @NoSuchCommand,
thanks for spotting this typo. 
Your PR has been merged, and the documentation will be updated very soon.
Benedikt
